name: Build SerenityOS Custom

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential cmake ninja-build qemu-system-x86 git python3 g++ clang lld \
            libgmp-dev libmpfr-dev libmpc-dev texinfo libz-dev libedit-dev

      - name: Configure environment
        run: |
          export SERENITY_ARCH=x86_64
          export SERENITY_TOOLCHAIN=Clang
          echo "SERENITY_ARCH=x86_64" >> $GITHUB_ENV
          echo "SERENITY_TOOLCHAIN=Clang" >> $GITHUB_ENV
          mkdir -p Build/x86_64

      - name: Build SerenityOS
        run: |
          bash Meta/serenity.sh build x86_64 Clang

      - name: Package ISO
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SerenityOS-ISO
          path: Build/x86_64/*.iso
