name: Build SerenityOS Custom

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ninja-build qemu-system-x86 git python3 g++ clang lld libgmp-dev libmpfr-dev libmpc-dev texinfo

      - name: Setup environment
        run: |
          echo "Using system Clang instead of Serenity toolchain"
          export SERENITY_TOOLCHAIN_PATH=/usr/bin
          echo "SERENITY_TOOLCHAIN_PATH=/usr/bin" >> $GITHUB_ENV
          mkdir -p Build/x86_64

      - name: Build system
        run: |
          bash Meta/serenity.sh build --use-system-compiler

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: SerenityOS-ISO
          path: Build/x86_64/*.iso
