name: Build SerenityOS Custom

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential cmake ninja-build qemu-system-x86 git python3 \
            g++ clang lld libgmp-dev libmpfr-dev libmpc-dev texinfo \
            libz-dev libedit-dev curl ccache tmux

      - name: Build toolchain
        run: bash Meta/serenity.sh rebuild-toolchain

      - name: Build system
        run: bash Meta/serenity.sh build x86_64 GNU

      - name: Create image
        run: bash Meta/serenity.sh image x86_64 GNU

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: SerenityOS-ISO
          path: Build/x86_64/*.iso
